server:
  port: 8891
spring:
  application:
    name: config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka

cloud:
  config:
    server:
      git:
        uri: https://github.com/FAuditore/1
        searchPaths: config

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh